var kGtId: String = ""
var kGtKey: String = ""
var kGtSecret: String = ""
var kUmKey = ""
var kUrl: String = ""
var kStatusBarColor: String = "#FFFFFF"
var kStatusBarLabelColor: String = "black"
var kAdjToken: String = ""
// TODO: 替换自己的Googleid
let GID_clientID = "141882578969-f2r3bgqlffce98kovg6oguheuarm45gq.apps.googleusercontent.com"
